name: Smoke-Test Fuzz Targets

on:
  workflow_call:

jobs:
  fuzz:
    env:
      CARGO_FUZZ_VERSION: 0.13.0
      FUZZ_TIME: 180

    strategy:
      matrix:
        include:
          - fuzz_target: fuzz_string
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4
      
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: cargo-fuzz
      
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-fuzz --version ${{ env.CARGO_FUZZ_VERSION }}
      
      - name: Fuzz
        working-directory: fuzz
        run: cargo fuzz run ${{ matrix.fuzz_target }} --release -- -max_total_time=${{ env.FUZZ_TIME }}
