name: Build and Test
description: Run build and test steps for the project

runs:
  using: composite
  steps:
    - name: Cargo Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -- --test-threads=1

